export const UserManagementData = [
  {
    course: 'Compensation and Benefits Policies',
    scoreAchieved: '-',
    timeTaken: '2hr 25min',
    noOfAttempts: '-',
    assignedDate: 'Jan 12, 2024',
    completedDate: 'Jan 12, 2024',
    taskStatus: 'Completed',
    subCourses: [
      {
        course: 'Salary Structure and Increments',
        scoreAchieved: '92.21%',
        timeTaken: '25 min',
        noOfAttempts: '04',
        assignedDate: '-',
        completedDate: '-',
        taskStatus: '-',
      },
      {
        course: 'Health and Wellness Benefits',
        scoreAchieved: '89.73%',
        timeTaken: '1hr 15min',
        noOfAttempts: '02',
        assignedDate: '-',
        completedDate: '-',
        taskStatus: '-',
      },
      {
        course: 'Retirement and Savings Plans',
        scoreAchieved: '93.25%',
        timeTaken: '45 min',
        noOfAttempts: '04',
        assignedDate: '-',
        completedDate: '-',
        taskStatus: '-',
      },
    ],
  },
  {
    course: 'Code of Conduct',
    scoreAchieved: '-',
    timeTaken: '-',
    noOfAttempts: '-',
    assignedDate: '-',
    completedDate: 'Feb 07, 2024',
    taskStatus: 'Completed',
    subCourses: [
      {
        course: 'Salary Structure and Increments',
        scoreAchieved: '92.21%',
        timeTaken: '25 min',
        noOfAttempts: '04',
        assignedDate: '-',
        completedDate: '-',
        taskStatus: '-',
      },
      {
        course: 'Health and Wellness Benefits',
        scoreAchieved: '89.73%',
        timeTaken: '1hr 15min',
        noOfAttempts: '02',
        assignedDate: '-',
        completedDate: '-',
        taskStatus: '-',
      },
      {
        course: 'Retirement and Savings Plans',
        scoreAchieved: '93.25%',
        timeTaken: '45 min',
        noOfAttempts: '04',
        assignedDate: '-',
        completedDate: '-',
        taskStatus: '-',
      },
    ],
  },
  {
    course: 'Administrative Details',
    scoreAchieved: '-',
    timeTaken: '-',
    noOfAttempts: '-',
    assignedDate: '-',
    completedDate: 'Feb 17, 2024',
    taskStatus: 'Completed',
  },
  {
    course: 'Job Role and Responsibilities',
    scoreAchieved: '-',
    timeTaken: '-',
    noOfAttempts: '-',
    assignedDate: '-',
    completedDate: 'Mar 14, 2024',
    taskStatus: 'Completed',
  },
  {
    course: 'Employee Benefits and Compensation',
    scoreAchieved: '-',
    timeTaken: '-',
    noOfAttempts: '-',
    assignedDate: '-',
    completedDate: 'Apr 04, 2024',
    taskStatus: 'Completed',
  },
]
