export const IconPack = {
    infoIcon : "/Skillsync-img/info-icon.svg",
    addTraining : "/Skillsync-img/add-training.svg",
    authBackground : "/Skillsync-img/authBackground.svg",
    caretIcon : "/Skillsync-img/caretIcon.svg",
    deleteRed : "/Skillsync-img/delete-red.svg",
    dropdownIcon : "/Skillsync-img/dropdownIcon.svg",
    dropdownIconup : "/Skillsync-img/dropdownIconup.svg",
    editBlack : "/Skillsync-img/edit-black.svg",
    editModule : "/Skillsync-img/edit-module.svg",
    filter : "/Skillsync-img/filter.svg",
    forgotPassword : "/Skillsync-img/forgotPassword.svg",
    graduationCap : "/Skillsync-img/graduation-cap-fill.svg",
    hide : "/Skillsync-img/hide.svg",
    home : "/Skillsync-img/home.svg",
    notification : "/Skillsync-img/notification.svg",
    paginationRight : "/Skillsync-img/paginationRight.svg",
    password : "/Skillsync-img/password.gif",
    search : "/Skillsync-img/search.svg",
    sentMail : "/Skillsync-img/sent-mail.gif",
    show : "/Skillsync-img/show.svg",
    trashIcon : "/Skillsync-img/trash-icon.svg",
    UserManagement : "/Skillsync-img/UserManagement.png",
    userphoto : "/Skillsync-img/userphoto.jpg",
    logo : "/Skillsync-img/logo.svg",
    cross : "/Skillsync-img/cross.svg",
    addTrainingGreen : "/Skillsync-img/add-training-green.png",
    greenTick:"/Skillsync-img/greenTick.svg",
    singleChoice:"/Skillsync-img/singleChoice.svg"
}
