export const Strings = {
  emailLink: 'Enter your email to get your link!',
  emailNotExist: 'Email does not exist',
  send: 'Send',
  clickEmailToReset: 'Please click on the link sent to your registered email to reset your password',
  reset: 'Reset',
  resetPassword: 'Reset Password',
  passwordRegain: 'Reset Your Password To Regain Access',
  ResetSuccessful: 'Password Reset Successful',
  signIn: 'Sign In',
  adminLogin: 'Admin Login: Access Your Dashboard',
  invalidEmailPassword: 'Invalid email or password',
  createAccount: 'Create an account',
  forgotPassword: 'Forgot password?',
  signUp: 'Sign Up',
  dashboard: 'Welcome to the Dashboard',
  username: 'User Name',
  admin: 'admin',
  logout: 'Logout',
  dashboardName: 'Dashboard',
  allCourses: 'All courses',
  userManagement: 'User Management',
  addNew: 'Add New',
  back: 'Back',
  publish: 'Publish',
  mandatory: 'Mandatory to all',
  trainings: 'Trainings',
  compliance: 'Compliance',
  learning: 'Learning',
  draft: 'Draft',
  active: 'Active',
  inactive: 'Inactive',
  save: 'Save',
  all: 'All',
  tableEmpty: 'Table is Empty',
  addCourses: 'Add Courses',
  add: 'Add',
  cancel: 'Cancel',
  update: 'Update',
  no: 'No',
  yes: 'Yes',
  addModulemsg: 'Add Module To Display Lessons',
  addLesson: 'Add lesson',
  test: 'Test',
  info: 'Create a dynamic test packed with at least 25 engaging questions!',
  selectType: 'Select Type',
  multipleChoice: 'Multiple choice',
  singleChoice: 'Single choice',
  addOption: 'Add option',
  addQuestion: 'Add Question',
  courseDetails: "Course Details"
}
